[[model]]
name = "火山方舟"
api_key = ""
api_url = "https://ark.cn-beijing.volces.com/api/plan"
[[model.models]]
name = "glm-5.3-flash"
image_vision = true

[[model.models]]
name = "glm-5.3"
image_vision = false
